version: "3"

services:
  source_database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: source_db
    ports:
      - "3307:3306"
    networks:
      - elt_network
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/init.sql

  target_database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: target_db
    ports:
      - "3308:3306"
    networks:
      - elt_network

  etl_tool:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ["python", "main.py"]
    networks:
      - elt_network
    volumes:
      - ./src/main.py:/app/main.py
    depends_on:
      - source_database
      - target_database

networks:
  elt_network:
    driver: bridge
